name: Python Testing Workflow

on:
  workflow_call:
    #inputs:
    #  name:
    #    description: "Your name"
    #    required: true
    #    default: "World"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install
      - name: Run tests
        run: |
          poetry run pytest
